# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean testDebug")
  end

  desc "Deploy Debug App to Google Play"
  lane :deploy_debug do
    gradle(task: "clean assembleDevelop",
      properties: {
        "android.injected.signing.store.file" => "release.keystore",
        "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
    # upload_to_play_store
  end

  desc "Deploy Release App to Google Play"
  lane :deploy_release do
    gradle(task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => "release.keystore",
        "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
    # upload_to_play_store
  end
end
