name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.x"

    - name: Gem caching
      id: gem_cache
      uses: actions/cache@v2
      continue-on-error: true
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Cache Gradle packages
      id: cache_gradle_packages
      uses: actions/cache@v2
      continue-on-error: true
      with:
        path: |
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/build-cache-*
        key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Bundle Install
      run: |
        gem install bundler:1.17.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Fastlane test
      env:
        API_CONTENTS: ${{ secrets.ASC_KEY_CONTENT }}
        STORE_FILE: ${{ secrets.KEYCHAIN_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ASC_KEY_ID }}
        KEY_PASSWORD: ${{ secrets.ASC_ISSUER_ID }}
      run: bundle exec fastlane test
