name: Test Actions

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: |
        echo running on branch ${GITHUB_REF##*/}
