name: Test Actions

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        echo ${{ github.event.name }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle