name: Test Actions

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Test
    if: startsWith(github.event.head_commit.message, '\deploy_debug')
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        echo ${{ github.event }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle